- .github/workflows/package.yaml
- setup_wizard/tests/constants.py
- setup_wizard/tests/models/test_operator_executioner.py
- setup_wizard/tests/test_driver.py
- setup_wizard/tests/test_setup_character.py
* Created a separate class that handles executing Setup Wizard Operators (ex. `import_character_model`, `delete_empties`, etc.)
* Refactored `test_setup_character` that leverages `TestOperatorExecutioner` (mentioned above) and tucks the logic into that class
* Now you just need to add a `TestOperatorExecutioner` object (with the necessary parameters) when adding new components!
* Separated test constants into it's own `constants.py`
* **Updated Github Action for packaging the Setup Wizard addon (remove tests before uploading the package)**
<br>
Side Note: The Github Action folder structure with the `mkdir` is set like that so that users can just take the uploaded zip file and immediately install it in Blender (no need to unzip, etc.)
* Setup_Wizard_Addon.zip > setup_wizard > [files, …
> refactor: automated test logic

- README.md
- setup_wizard/README.md
* Updated path reference to Festivity's Outlines
* Updated BetterFBX support notes
* Fixed README reference to the Setup Wizard README (it was just going to the Setup Wizard folder)
> chore: updated README files 

- setup_wizard/__init__.py
- setup_wizard/genshin_import_material_data.py
- setup_wizard/material_data_applier.py
* Alpha Options in the shader were not being set up when importing material data
* Added mapping between the material data and the Alpha Options in the shader
> feat: material data sets up alpha options in shader

- README.md
- setup_wizard/README.md
* Updated repository README and Setup Wizard README
> doc: Update README files

- setup_wizard/material_data_import_setup/material_data_applier.py
- Shadow ramp color using Material Data (thanks Bonny for looking into this and providing details)
- _CoolShadowMultColor - Night
- FirstShadowMult - Day
Closes #45
> feat: NPC shadow ramp color support using material data

- setup_wizard/__init__.py
> chore: bump Setup Wizard addon version to v1.2.1

- setup_wizard/config_ui.json
- setup_wizard/domain/shader_identifier_service.py
- setup_wizard/genshin_setup_wizard.py
- setup_wizard/geometry_nodes_setup/geometry_nodes_setups.py
- setup_wizard/import_order.py
- setup_wizard/material_data_import_setup/material_data_applier.py
- setup_wizard/misc_operations.py
- setup_wizard/replace_default_materials_setup/game_default_material_replacers.py
- setup_wizard/texture_import_setup/texture_importer_types.py
- setup_wizard/texture_import_setup/texture_node_names.py
- setup_wizard/ui/gi_ui_setup_wizard_menu.py
- setup_wizard/ui/hsr_ui_setup_wizard_menu.py
- Add character name to shader materials on setup
- Remove rigging error pop-up when attempting to rig NPCs/Monsters (only playable character supported)
- Additional V3 support and changes
> feat: add character name to shader materials and remove rigging error pop-up

- setup_wizard/__init__.py
- setup_wizard/character_rig_setup/rig_script.py
1. Fixes pupil controls not working on face panel when joining meshes
> fix: pupil controls on face panel when joining meshes (refactor getting ShapeKey index)

- .github/workflows/package.yaml
- setup_wizard/character_rig_setup/character_rigger_operator.py
- setup_wizard/character_rig_setup/rig_script.py
- setup_wizard/join_meshes_on_armature/join_meshes_operator.py
- setup_wizard/ui/gi_ui_setup_wizard_menu.py
- UI (N-Panel)
- `Rigging Enabled` and `Join Meshes Enabled` are global toggles (enabled/disabled for `Run Entire Setup` and `Basic Setup`
- Rigging Adjustments (:star: Thanks **Enthralpy** for providing the updates! :star: )
- Setup Neck and Head Follow, set to `1.0`
- Scaling fingers on X-Axis will curl fingertips
- Internal Changes
- Updates to Github Action Workflow (addon packaging process)
> feat: global toggles and adjustments to rigging script

- .github/workflows/package.yaml
- setup_wizard/domain/shader_identifier_service.py
- setup_wizard/domain/shader_material_names.py
- setup_wizard/replace_default_materials_setup/game_default_material_replacers.py
- setup_wizard/texture_import_setup/texture_importer_types.py
- setup_wizard/utils/genshin_body_part_deducer.py
* Adds shader setup support for Genshin Impact NPCs with an Item mesh and material
> feat: NPC Item Setup Support

- setup_wizard/__init__.py
Forgot to bump it previously in #81
> chore: bump Character Setup Wizard addon (2.2.1)

- setup_wizard/__init__.py
- setup_wizard/character_rig_setup/npc_rig_script.py
- setup_wizard/character_rig_setup/rig_script.py
- also fixes arm deformation bones being wonky
- code fix by: Enthralpy
> fix: children hand bones rotated 90 degrees sideways

- setup_wizard/__init__.py
- setup_wizard/config_ui.json
- setup_wizard/domain/shader_identifier_service.py
- setup_wizard/domain/shader_material_names.py
- setup_wizard/domain/shader_node_names.py
- setup_wizard/genshin_import_character_model.py
- setup_wizard/genshin_import_material_data.py
- setup_wizard/genshin_import_materials.py
- setup_wizard/genshin_import_outlines.py
- setup_wizard/genshin_setup_wizard.py
- setup_wizard/geometry_nodes_setup/geometry_nodes_setups.py
- setup_wizard/import_order.py
- setup_wizard/material_data_import_setup/game_material_data_importers.py
- setup_wizard/material_data_import_setup/material_data_applier.py
- setup_wizard/material_import_setup/empty_names.py
- setup_wizard/material_import_setup/game_material_importers.py
- setup_wizard/misc_final_steps.py
- setup_wizard/misc_operations.py
- setup_wizard/outline_import_setup/outline_importers.py
- setup_wizard/outline_import_setup/outline_node_groups.py
- setup_wizard/replace_default_materials_setup/game_default_material_replacers.py
- setup_wizard/tests/test_honkai_star_rail_character_setup.py
- setup_wizard/texture_import_setup/outline_texture_importers.py
- setup_wizard/texture_import_setup/texture_importer_types.py
- setup_wizard/texture_import_setup/texture_node_names.py
- setup_wizard/ui/hsr_ui_setup_wizard_menu.py
> feat: StellarToon Support

- setup_wizard/material_data_import_setup/game_material_data_importers.py
1. Adds smart searching for selecting material data files for HSR
a. No more needing to select the Material Data JSON files (for most characters at least?)
b. Same feature that has existed for Genshin Impact Character Setup
> feat: material data import smart search for HSR

- setup_wizard/domain/shader_identifier_service.py
- setup_wizard/domain/shader_material_names.py
- setup_wizard/material_data_import_setup/game_material_data_importers.py
- setup_wizard/misc_operations.py
- setup_wizard/replace_default_materials_setup/game_default_material_replacers.py
- setup_wizard/tests/test_genshin_impact_character_setup.py
- setup_wizard/tests/test_honkai_star_rail_character_setup.py
- setup_wizard/tests/test_punishing_gray_raven_character_setup.py
- setup_wizard/texture_import_setup/texture_importer_types.py
- setup_wizard/ui/hsr_ui_setup_wizard_menu.py
1. Material Data Targeting for HSR
2. Rename shader materials with character name for HSR
1. Enable SSR (Advanced Setup) was not passing required GameType in
2. Sampo Handbag Setup
> feat: feature parity between setup for GI and HSR

- setup_wizard/domain/shader_node_names.py
- setup_wizard/material_data_import_setup/game_material_data_importers.py
- setup_wizard/misc_operations.py
- setup_wizard/tests/test_driver.py
- setup_wizard/texture_import_setup/texture_importer_types.py
1. Enable Stockings constant
2. Renamed material data class to better fit its usage (`MaterialDataDirectory`)
3. Fix test directory lookup to handle a certain character
4. Added comments
> refactor: renaming data structures, adding constants, fixing tests

- setup_wizard/__init__.py
- setup_wizard/config_ui.json
- setup_wizard/domain/shader_node_names.py
- setup_wizard/geometry_nodes_setup/geometry_nodes_setups.py
- setup_wizard/material_data_import_setup/game_material_data_importers.py
- setup_wizard/material_data_import_setup/material_data_applier.py
- setup_wizard/misc_final_steps.py
- setup_wizard/replace_default_materials_setup/game_default_material_replacers.py
- setup_wizard/texture_import_setup/outline_texture_importers.py
- setup_wizard/texture_import_setup/texture_importer_types.py
- setup_wizard/ui/gi_ui_setup_wizard_menu.py
- setup_wizard/utils/genshin_body_part_deducer.py
1. Aranara Support
2. Support for latest Genshin Shader version
1. Removed ArmTwist Bone Constraints
1. HSR Transparency fixes (Asta, Herta, etc.)
2. Material data import error message was hardcoded and now relevant to the shader being used (StellarToon or Nya222)
> feat: support for latest Genshin shader version, Aranara support, HSR transparency fixes

- setup_wizard/__init__.py
- setup_wizard/replace_default_materials_setup/game_default_material_replacers.py
- setup_wizard/texture_import_setup/texture_importer_types.py
- setup_wizard/texture_import_setup/texture_node_names.py
1. Stocking texture not set in Stockings node group
2. Mat_Trans material not being replaced with Body_Trans material
> fix: HSR stocking texture not set and transparency material not replaced

- setup_wizard/replace_default_materials_setup/game_default_material_replacers.py
- setup_wizard/texture_import_setup/texture_importer_types.py
1. Support for unique material names; fallback and apply Body shader to material
1. Fix transparency being applied to all weapon materials (should only be WEAPON_TRANS material)
> feat: HSR New Material Name Fallback Support

- setup_wizard/__init__.py
Forgot to bump addon version as part of #133
> chore: bump Character Setup Wizard addon (2.6.4)
