michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders

setup_wizard/README.md
setup_wizard/config_ui.json
setup_wizard/genshin_setup_wizard.py
setup_wizard/ui_setup_wizard_menu.py

* Do not render buttons for Outlines if the Blender version is < v3.3.0
* Do not include Outlines in "One-Click" Simplified Setup if the Blender version is < v3.3.0

fix/feat: handle blender versions < v3.3.0

---

setup_wizard/exceptions.py
setup_wizard/genshin_import_material_data.py
setup_wizard/parsers/data_classes.py
setup_wizard/parsers/material_data_json_parsers.py

* Created HoyoStudio and UABE material JSON parsers
* To add additional JSON parsers:
1. Create a new class that inherits `MaterialDataJsonParser`
2. Write the parsing logic
3. Add it to the `parsers` list in `genshin_import_material_data.py`
* Refactored component that imports material data
* duplicate logic consolidated into a single method
* Provide slightly more user-friendly info/error messages

feat: framework and support for multiple material data json formats

---

setup_wizard/genshin_import_character_model.py
setup_wizard/genshin_import_material_data.py
setup_wizard/genshin_import_materials.py
setup_wizard/genshin_import_outline_lightmaps.py
setup_wizard/genshin_import_outlines.py
setup_wizard/genshin_import_textures.py
setup_wizard/genshin_set_up_geometry_nodes.py
setup_wizard/import_order.py
setup_wizard/models.py

* Decreased default outline thickness from `1.0` to `0.25` after recent shader change
* https://github.com/festivize/Blender-miHoYo-Shaders/commit/bbf6c8f22fea9f5b20b5562123243a5666a51294
* Reset custom properties at the end of components that take in user file/folder selections
* Unexpected state behavior was occurring because the module is registered and values carry over from one usage to the next usage
* Running the `Entire Setup Wizard` and then running individual components would result in running every step after the individual component too
* For example, running `Entire Setup Wizard` and then `Import Material Data` would also result in `Fix Transformations` to be run
* Added a warning message when the user selects a Material Data JSON that does not match up with a Material (ex. …

feat: decrease default outline thickness and reset custom properties at the end of a component

---

setup_wizard/genshin_set_up_geometry_nodes.py

* Create outlines for Face (nose bridge)
* No longer create geometry nodes for the Brow mesh
* Paimon does not have a Brow and is not used anywhere

fix: missing outlines for Face and creation of outlines for Brow

---

setup_wizard/genshin_import_character_model.py
setup_wizard/genshin_import_outline_lightmaps.py
setup_wizard/genshin_import_textures.py
setup_wizard/genshin_set_up_geometry_nodes.py
setup_wizard/import_order.py
setup_wizard/misc_operations.py

* New character meshes are named differently (numbered) so check if the expected mesh name is in the object name instead of an exact object name check
* `object.name == 'EffectMesh'` vs `'EffectMesh' in object.name`
* Refactored importing character textures to use `bpy.data.materials` instead of `bpy.context`
* This allows us to access and update the material directly instead of relying on the active object (which is a little more difficult with the new characters and their numbered mesh format)

refacor/fix: handle new characters

---

setup_wizard/genshin_set_up_geometry_nodes.py

Quick fix. We should be searching for `###_{mesh_name}` not `{mesh_name}.###` for some character(s) when creating geometry nodes (outlines) for them.
The issue ended up causing no outlines to be created, which is not a catastrophic issue, but you'd need to then manually set up the outlines for them.

fix: incorrect mesh name format to create outlines on

---

setup_wizard/__init__.py
setup_wizard/genshin_import_material_data.py
setup_wizard/genshin_import_outline_lightmaps.py
setup_wizard/genshin_import_textures.py
setup_wizard/genshin_setup_wizard.py
setup_wizard/ui_setup_wizard_menu.py

Pre-Release early access support for Festivity's shader rewrite.
- No longer need to plug normal map
- Outline lightmap node was renamed
- A new node for diffuse texture be assigned for Outlines
- Material data - tons of new values and some old ones were renamed or removed

feat: support for festivity shader rewrite

---

setup_wizard/README.md
setup_wizard/genshin_import_materials.py
setup_wizard/genshin_import_outline_lightmaps.py
setup_wizard/import_order.py
setup_wizard/material_data_applier.py
setup_wizard/tests/character_filename_to_material_data_mapper.py
setup_wizard/tests/config.json.sample
setup_wizard/tests/constants.py
setup_wizard/tests/test_driver.py
setup_wizard/tests/test_setup_character.py

- Added ability to select a specific blend file for importing materials (select either Vanilla or Goo `.blend` file)
- Updated tooltip to mention selecting the specific `.blend` file
- You can still select Festivity's shader folder (backwards compatible/fallback check), but going forward I'd like to move people to selecting the exact `.blend` file they want to import materials from)
- Made tests be runnable with different configurations to provide confidence that new changes do not break existing workflows
- Goo Blender, Vanilla Blender
- Old Import Materials (select Festivity folder), New Import Materials (select `.blend` file)
- V1 Festivity shader, V2 Festivity shader
- Refactoring, refactoring and more refactoring

feat: ability to select blend file with materials and some refactoring

---

setup_wizard/parsers/data_classes.py

* As requested, set `_MTSharpLayerOffset` to `1.0` when it does not exist in the material data JSON file
* I think this disables it in the shader?

feat: set default _MTSharpLayerOffset value when it does not exist in material data

---

setup_wizard/genshin_import_character_model.py
setup_wizard/tests/config.json.sample
setup_wizard/tests/test_driver.py
setup_wizard/ui_setup_wizard_menu.py

* Added (experimental) BetterFBX support
* When I say experimental, I mean that I don't know what exact parameters should be passed through to BetterFBX by default...
* Currently using all default parameters and just passing in the `.fbx` file to import
* BetterFBX import is enabled by default if it's installed, but can be unchecked to turn it off to revert back to Blender's vanilla FBX import (has `force_connect_children` = `True` and `automatic_bone_orientation` = `True`)
* Also made tests configurable to enable/disable BetterFBX for testability

feat: implement (experimental) betterfbx support

---

setup_wizard/genshin_import_material_data.py
setup_wizard/material_data_applier.py

* Apply Emission Tint using material data
* Bugfix where all MaterialDataAppliers (V2 and V1) would try applying data, even if one of them (ex. V2) had already successfully applied material data
* No impact on the end result (as it would just reapply the same value, but it could've lead to a future bug)

feat: apply Emission Tint using material data + material data bugfix

---

setup_wizard/genshin_import_material_data.py
setup_wizard/material_data_applier.py

- Added support for applying weapon material data
- Currently `V2_WeaponMaterialDataApplier` is the same as `V2_MaterialDataApplier`, I kept the design I initially thought of in case the material data applying deviates from each other down the road (unlikely, but possible)

feat: support for applying weapon material data

---

setup_wizard/__init__.py
setup_wizard/genshin_import_character_model.py
setup_wizard/genshin_set_up_geometry_nodes.py

Adds support for Blender v3.4 by addressing the following issues:
- Closes #27
- Closes #28
- Renames all mesh `Color Attributes` to `Col`
- Reorders `Face` mesh's material slots (adds temporary material slot, swaps material slots, removes temporary material slot

fix: broken shader/outlines in Blender v3.4

---

setup_wizard/genshin_import_character_model.py
setup_wizard/genshin_import_materials.py
setup_wizard/genshin_set_up_geometry_nodes.py
setup_wizard/utils/material_utils.py

Adds fake users to all imported materials during the Setup Wizard setup process to prevent Blender garbage collection from removing required materials when reopening the file
- Adds fake user to materials when importing character model, shader materials and shader material outlines
- Prevents Blender garbage collection from removing these required materials
- Closes #30

feat: add fake user to all imported materials during setup

---

setup_wizard/genshin_replace_default_materials.py

* Dress materials not getting fake users assigned to them, which can cause them to be deleted if they are not assigned and the file is saved and reopened
* Closes #30

fix: Dress materials not getting fake users assigned

---

setup_wizard/domain/shader_configurator.py
setup_wizard/domain/texture_importers.py
setup_wizard/genshin_import_character_model.py
setup_wizard/genshin_import_materials.py
setup_wizard/genshin_import_textures.py
setup_wizard/genshin_replace_default_materials.py

* Now correctly replaces NPC materials with shader materials
* Now correctly assigns NPC textures to shader materials
* Since NPCs don't have/use shadow ramps, shadow ramps are DISABLED (value set to `0`) on setup if:
1. The NPC's original material names **does not** have `Avatar` in it (this is how we determine if whether it's an NPC or Playable Character)
2. No shadow ramp assets are found in the same directory as the other textures
* Refactored texture importing
* Add fake users to all shader materials that are imported
* Added some TODOs to look into later
NPC textures are named differently then Avatar (playable characters) textures and so there is a class for each. The factory pattern is leveraged to create a `GenshinTextureImporter`. It doesn't matter whether it returns a …

feat: initial Setup Wizard NPC support

---

README.md
setup_wizard/README.md
setup_wizard/__init__.py
setup_wizard/config_ui.json
setup_wizard/domain/texture_importers.py
setup_wizard/genshin_import_outline_lightmaps.py
setup_wizard/genshin_setup_wizard.py
setup_wizard/import_order.py
setup_wizard/misc_operations.py
setup_wizard/tests/test_setup_character.py
setup_wizard/ui_setup_wizard_menu.py

* Reorients ArmTwist bones towards the Forearm Head (A01 and A02, if they exist)
* Sets up Copy Rotation bone constraints on the ArmTwist bones
* Fix Face Shadow/Face Lightmap textures not being imported correctly for a certain traveling companion
* Setup Wizard for NPCs breaks when trying to import outline diffuse/lightmap for Outlines
* Update README
* Bump Addon Version
* Minor updates to automated tests

feat: Set Up ArmTwist Bone Constraints

---

setup_wizard/ui_setup_wizard_menu.py

Yep, that's pretty much it. 
Display the addon version number in the UI so it's easier to identify what addon version a user is using.

feat: display addon version number on UI to help w/ troubleshooting

---

setup_wizard/__init__.py
setup_wizard/domain/character_types.py
setup_wizard/domain/outline_material_data.py
setup_wizard/domain/shader_configurator.py
setup_wizard/exceptions.py
setup_wizard/genshin_import_material_data.py
setup_wizard/genshin_replace_default_materials.py
setup_wizard/import_order.py
setup_wizard/material_data_import_setup/game_material_data_importers.py
setup_wizard/material_data_import_setup/material_data_applier.py
setup_wizard/replace_default_materials_setup/game_default_material_replacers.py
setup_wizard/texture_import_setup/game_texture_importers.py
setup_wizard/texture_import_setup/outline_texture_importers.py
setup_wizard/texture_import_setup/texture_importer_types.py
setup_wizard/ui/gi_ui_setup_wizard_menu.py
setup_wizard/utils/genshin_body_part_deducer.py

Some old commits from a few months ago.
* Adds support for some NPC and Monster setup (like Eremites, Fatui, etc.)
* New feature to target materials (the Target Material and Outlines Material) for importing material data

feat: Character Setup Wizard basic NPC and Monster support

---

setup_wizard/outline_import_setup/outline_node_groups.py

Fixes broken geometry nodes setup due to Setup Wizard expecting and looking for a different node group name.
- https://github.com/festivities/Blender-miHoYo-Shaders/blob/main/Genshin%20-%20Outlines.blend

chore: update node group name for latest version of outlines file

---

setup_wizard/domain/shader_node_names.py
setup_wizard/material_data_import_setup/material_data_applier.py
setup_wizard/texture_import_setup/texture_importer_types.py

* Use `Hair` output for `Face` material on Furina (instead of `Body` output)

fix: Furina - Use Hair Output for Face material / GI V3 Shader Support

---

setup_wizard/material_import_setup/game_material_importers.py

1. PGR Setup on Blender 4.0
a. Head empties were not being appended because Light Direction empty existed
b. Now tries to append all empties that don't exist instead of appending only if none of the expected empties do not exist
While the fix is for PGR, the updated logic is written for all shaders.

fix: PGR Setup on Blender 4.0

---

setup_wizard/__init__.py

- let's keep release it at 2.4.0.1

revert: bump Character Setup Wizard addon (2.4.1)

---

.github/workflows/package.yaml
setup_wizard/__init__.py
setup_wizard/genshin_setup_wizard.py

1. Ensures auto-dependency setup works for Blender 3.6 and 4.0
1. Auto-create release with artifacts

refactor: auto-dependency setup works for Blender 3.6 and 4.0

---

setup_wizard/__init__.py
setup_wizard/material_data_import_setup/material_data_applier.py

fix: material data not applying for older genshin shader versions; broken since 2.4.1 (75eeddd)

fix: material data not applied for older Genshin shader versions

---

setup_wizard/character_rig_setup/npc_rig_script.py
setup_wizard/character_rig_setup/rig_script.py

ColorPickers were stashed in the rig object, so they are now also driven by the visibility of the Lighting layer.

Added visibility drivers to ColorPicker objects stashed in the Rig object

---

setup_wizard/character_rig_setup/npc_rig_script.py
setup_wizard/character_rig_setup/rig_script.py

Reverts michael-gh1/Addons-And-Tools-For-Blender-miHoYo-Shaders#116
We realized these were from empties we don't actually want in the character rig. Keep them in `wgt` collection

revert: "Added visibility drivers to ColorPicker objects stashed in the Rig object"

---

setup_wizard/character_rig_setup/hsr_rig_script.py

Fix the issue where if a character didn't have a "joint_skin_GRP" bone, the rigify script would throw exception.
Some characters (in my case Sam) do not have face bones, so naturally the `joint_skin_GRP` and `joint_face` bones would not be present.

fix: issue with rigging crashing for characters without faces

---

setup_wizard/__init__.py
setup_wizard/geometry_nodes_setup/geometry_nodes_setups.py

1. Fixes `EyeStar` being black after rigging setup

fix: EyeStar is black after rigging; requires Light Vector setup
